.SILENT:

mergesort: compile
	g++ -o src/mergesort src/mergesort.cpp
	./src/mergesort


quicksort: compile
	g++ -o src/quicksort src/quicksort.cpp
	./src/quicksort
compile:
	g++ -o src/data src/Data.cpp
	./src/data

clean:
	-rm -f *.bin core
